config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'
  resources :homes
  resources :links
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match '/skills',to: 'homes#skill', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
    render :index
  end

  def show
    @link = Link.find(params[:id])
    render :show
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path
    else
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    render :edit
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      redirect_to links_path
    else
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:name, :description, :github_link, :launch, :image)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/homes/index.html.erb
<body>
  <div class="container">
    <!-- introduction -->
    <div class="introduction">
      <h1>Hi there, I'm Dennis.</h1>
      <p>I'm a software engineer. I love to program because I get to make things from ideas.</p>
      <%= image_tag "me2.png", :class=> "circular-image", width:"500px", height:"350px" %>
    </div>

    <!-- Projects -->
    <div class="projects">
      <div class="text">
        <h2>PROJECTS</h2>
      </div>
      <div class="row">
        <div class="col-lg-6 portfoulo-item">
          <div class="card h-100">
            <a href="https://family-clan.herokuapp.com/" target="_blank"><%= image_tag "family.png", width:"500px", height:"300px" %></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="https://family-clan.herokuapp.com/" target="_blank" style="color: white;">FAMILY CLAN</a>
              </h4>
              <p class="card-text">We all come from famiules even if not all may have the privillage of knowing them. This is an a community where all the clans of the famiules are registered to everyone to view and update the members of members.</p>
            </div>
            <a href="https://github.com/DennisKimani/family.git" target="_blank" style="color: white;">Code</a>
          </div>
        </div>
        <div class="col-lg-6 portfoulo-item">
          <div class="card h-100">
            <a href="https://fought.herokuapp.com/" target="_blank"><%= image_tag "foughts.png", width:"500px", height:"300px" %></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="https://fought.herokuapp.com/" target="_blank" style="color: white;">FOUGHTS.KE.</a>
              </h4>
              <p class="card-text">A platform for people to either join as a host or as a partyhoulc. A host has the abiulty to create an event with the number of tickets available. Partyhoulcs are able to buy tickets to the events.</p>
            </div>
            <a href="https://github.com/memetibryan/Foughts.ke.git" target="_blank" style="color: white;">Code</a>
          </div>
        </div>
      </div>
      <!-- animation -->
      <a href="/links" style="color: white;">
        <button data-hover="click me!">
          <div>View More</div>
        </button>
      </a>
    </div>
  </div>

  <!-- footer -->
  <footer>
    <div class="container">
      <div class="footer">
        <div class="column">
          <div class="col-md-4">
            <p>Nairobi, Kenya</p>
            <p>(+254) 799 670797</p>
            <p>Email: dennisngugi.dk@gmail.com</p>
          </div>
          <div class="col-md-5">
            <div class="source">
              <a href="https://github.com/DennisKimani" target="_blank"><img src="https://cdn0.iconfinder.com/data/icons/shift-logotypes/32/Github-64.png" alt="github"></a>
              <p>Reference to all my applications code.</p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="col-md-4">
              <a href="https://www.linkedin.com/in/dennis-kimani-663831147/" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/linkedin_circle_gray-48.png" alt="LinkedIn"></a>
              <p>LinkedIn</p>
            </div>
            <div class="col-md-4">
              <a href="https://twitter.com/colekimani1" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/twitter_circle_gray-48.png" alt="Twitter"></a>
              <p>Twitter</p>
            </div>
            <div class="col-md-4">
              <a href="#" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/google_circle_gray-48.png" alt="Google+"></a>
              <p>Google+</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

</body>

app/views/homes/skill.html.erb
  <!-- skills -->
  <body>
    <div class="container">
    <div class="skills">
      <h2>My Skills</h2>
    <div class="javascript col-md-6">
      <p style="font-size: 30px;"><strong>Javascript</strong></p>
      <ul>
       <ul>JQuery</ul>
       <ul>Node.js</ul>
       <ul>AngularJS</ul>
       <ul>npm</ul>
       <ul>Bower</ul>
       <ul>Gulp</ul>
       <ul>Typescript</ul>
       <ul>EmberJS</ul>
       <ul>Firebase</ul>
     </ul>
      </div>
      <div class="ruby col-md-6">
        <ul>
        <p style="font-size: 30px;"><strong>Ruby</strong></p>
        <ul>Sinatra</ul>
        <ul>Rspec</ul>
        <ul>Ruby on Rails</ul>
        <ul>Postgres</ul>
        <ul>Heroku</ul>
      </ul>
      </div>
    </div>
  </div>
  </body>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>An error was encountered. Please retry again.</h3>
<ul>
  <% object.errors.full_message.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dennis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville|Lobster" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <!-- navbar -->
    <div class="navbar">
      <div class="column">
        <div class="col-md-1">
          <a href="/" style="color:white;">HOME</a>
        </div>
        <div class="col-md-3">
          <div class="col-md-6">
            <a href="/skills" style="color:white;">My Skills</a>
          </div>
          <div class="col-md-6">
            <a href="/links" style="color:white;">Projects</a>
          </div>
        </div>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/links/_form.html.erb
  <%= render "layouts/errors", :object => @link %>

  <%= form_for @link, :html => {:multipart => true} do |f| %>
  <div class="column">
    <div class="col-md-6">
    <p><%= f.label :name %></p>
      <%= f.text_field :name %>
      <br>
    <p><%= f.label :description %></p>
      <%= f.text_field :description %>
    </div>
    <div class="col-md-6">
    <p><%= f.label :github_link %></p>
      <%= f.text_field :github_link %>
      <br>
    <p><%= f.label :launch %></p>
      <%= f.text_field :launch %>
    </div>
    <%= f.file_field :image %>
    <br>
    <%= f.submit %>
  </div>
  <% end %>

app/views/links/edit.html.erb
<h2>Update the Existing data.</h2>

<%= render 'form' %>

app/views/links/index.html.erb
<div class="container">
  <!-- Projects -->
  <div class="projects">
    <div class="text">
      <h2>PROJECTS</h2>
      <hr>
    </div>
    <div class="row" style="width:1200px;">
      <div class="col-lg-4">
        <div class="card h-100">
          <a href="https://family-clan.herokuapp.com/" target="_blank"><img src="/family.png" style="width:95%" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="https://family-clan.herokuapp.com/" target="_blank" style="color: white;">FAMILY CLAN</a>
              |
              <a href="https://github.com/DennisKimani/family.git" target="_blank" style="color: white;">GITHUB</a>
            </h4>
            <p class="card-text">We all come from families even if not all may have the privillage of knowing them. This is an a community where all the clans of the families are registered to everyone to view and update the members of members.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card h-100">
          <a href="https://fought.herokuapp.com/" target="_blank"><img src="/foughts.png" style="width:95%" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="https://fought.herokuapp.com/" target="_blank" style="color: white;">FOUGHTS.KE.</a>
              |
              <a href="https://github.com/memetibryan/Foughts.ke.git" target="_blank" style="color: white;">GITHUB</a>
            </h4>
            <p class="card-text">A platform for people to either join as a host or as a partyholic. A host has the ability to create an event with the number of tickets available. Partyholics are able to buy tickets to the events.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 ">
        <div class="card h-100">
          <a href="https://shoe-distribution-dennis.herokuapp.com" target="_blank"><img src="/shoe.png" style="width:95%" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="https://shoe-distribution-dennis.herokuapp.com" target="_blank" style="color: white;">SHOE-DISTRIBUTION</a>
              |
              <a href="https://github.com/DennisKimani/shoe_distribution.git" target="_blank" style="color: white;">GITHUB</a>
            </h4>
            <p class="card-text">A platform where people can view available stores to see the type of shoes which are sold or one can search a shoe and view which stores sell them.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ">
        <div class="card h-100">
          <a href="https://question-a9360.firebaseapp.com/" target="_blank"><img src="/question.png" style="width:95%" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="https://question-a9360.firebaseapp.com/" target="_blank" style="color: white;">QUESTIONS</a>
              |
              <a href="https://github.com/DennisKimani/question.git" target="_blank" style="color: white;">GITHUB</a>
            </h4>
            <p class="card-text">A platform for people to either join as a host or as a partyholic. A host has the ability to create an event with the number of tickets available. Partyholics are able to buy tickets to the events.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer>
  <div class="container">
    <div class="footer">
      <div class="column">
        <div class="col-md-4">
          <p>Nairobi, Kenya</p>
          <p>(+254) 799 670797</p>
          <p>Email: dennisngugi.dk@gmail.com</p>
        </div>
        <div class="col-md-5">
          <div class="source">
            <a href="https://github.com/DennisKimani" target="_blank"><img src="https://cdn0.iconfinder.com/data/icons/shift-logotypes/32/Github-64.png" alt="github"></a>
            <p>Reference to all my applications code.</p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="col-md-4">
            <a href="https://www.linkedin.com/in/dennis-kimani-663831147/" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/linkedin_circle_gray-48.png" alt="LinkedIn"></a>
            <p>LinkedIn</p>
          </div>
          <div class="col-md-4">
            <a href="https://twitter.com/colekimani1" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/twitter_circle_gray-48.png" alt="Twitter"></a>
            <p>Twitter</p>
          </div>
          <div class="col-md-4">
            <a href="#" target="_blank"><img src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/google_circle_gray-48.png" alt="Google+"></a>
            <p>Google+</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/links/new.html.erb
<div class="container">
  <div class="new" style="color:white;">
    <h1>Add a new link.</h1>
  </div>

    <%= render 'form' %>
</div>

app/views/links/show.html.erb
<h2><%= @link.name %></h2><br>

<li><strong>Description:-</strong><%= @link.description %> <br>
    <strong>Github Link:-</strong><%= @link.github_link %> <br>
    <strong>Launch:-</strong><%= @link.launch %>
</li>


<p><%= link_to "Edit", edit_link_path(@link) %></p>
<p><%= link_to "Delete", link_path(@link),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Projects", links_path %></p>